name       : m17n-lib
version    : 1.7.0
release    : 4
source     :
    - http://download.savannah.gnu.org/releases/m17n/m17n-lib-1.7.0.tar.gz : 8eb853e1e0c86a70a09871f3264f950e5d62bba98960b3ffcde11511c138db83
license    : LGPL-2.1
component  : programming
summary    : The m17n library is a multilingual text processing library for the C language
description: |
    The m17n library is a multilingual text processing library for the C language
builddeps  :
    - pkgconfig(anthy)
    - pkgconfig(fribidi)
    - pkgconfig(xft)
    - pkgconfig(xt)
rundeps    :
    - m17n-db
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install -j1
    rm -rf $installdir/usr/share
